echo Starting sync process...
cd /d "D:\code-Portfolio"

echo Pulling latest changes from GitHub...
git pull origin main

echo Adding all changes...
git add .

echo Committing changes...
set /p commit_msg="Enter commit message: "
git commit -m "%commit_msg%"

echo Pushing to GitHub...
git push origin main